// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class JournalEntry {
  static encode(message: JournalEntry, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.title);

    writer.uint32(26);
    writer.string(message.message);
  }

  static decode(reader: Reader, length: i32): JournalEntry {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new JournalEntry();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.title = reader.string();
          break;

        case 3:
          message.message = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  title: string;
  message: string;

  constructor(id: string = "", title: string = "", message: string = "") {
    this.id = id;
    this.title = title;
    this.message = message;
  }
}
